# Generated by Django 5.2.8 on 2025-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Cuộc gọi'), ('EMAIL', 'Email'), ('MEETING', 'Cuộc họp'), ('NOTE', 'Ghi chú')], max_length=20)),
                ('summary', models.TextField(verbose_name='Nội dung hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên giao dịch')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá trị dự kiến')),
                ('expected_close_date', models.DateField(verbose_name='Ngày đóng dự kiến')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('WON', 'Thắng (Thành công)'), ('LOST', 'Thua (Thất bại)')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên giai đoạn')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
