# Generated by Django 5.2.8 on 2025-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='type',
            field=models.CharField(choices=[('OPEN', 'Đang xử lý (Open)'), ('WON', 'Thắng (Won)'), ('LOST', 'Thua (Lost)')], default='OPEN', max_length=10),
        ),
    ]
