# Generated by Django 5.2.8 on 2025-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0004_pipelinestage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá niêm yết')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
