# Generated by Django 5.2.8 on 2025-12-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá thực bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_pipeline.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales_pipeline.product')),
            ],
        ),
    ]
