# Generated by Django 5.2.8 on 2025-12-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0007_alter_opportunity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do thất bại'),
        ),
    ]
