# Generated by Django 5.2.8 on 2025-12-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0008_opportunity_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason_code',
            field=models.CharField(blank=True, choices=[('PRICE', 'Giá quá cao'), ('COMPETITOR', 'Đối thủ tốt hơn'), ('FEATURES', 'Thiếu tính năng/Sản phẩm'), ('TIMING', 'Không đúng thời điểm'), ('BUDGET', 'Hết ngân sách'), ('OTHER', 'Lý do khác')], max_length=20, null=True, verbose_name='Mã lý do thua'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lost_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết lý do'),
        ),
    ]
