# Generated by Django 5.2.8 on 2025-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Trưởng phòng KD'), ('REP', 'Nhân viên KD')], default='REP', max_length=50),
        ),
    ]
